name: Sync Docker Images (Selective Arch)

on:
  workflow_dispatch:
    inputs:
      arch:
        description: "Select architecture to sync"
        required: true
        type: choice
        options:
          - arm64
          - amd64

env:
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
  NAMESPACE_AMD64: "${{ secrets.NAMESPACE_AMD64 }}"
  NAMESPACE_ARM64: "${{ secrets.NAMESPACE_ARM64 }}"
  ALIYUN_USERNAME: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Aliyun
        run: |
          docker login -u $ALIYUN_USERNAME -p $ALIYUN_PASSWORD $ALIYUN_REGISTRY

      - name: Select image list
        id: list
        run: |
          if [ "${{ github.event.inputs.arch }}" = "arm64" ]; then
            echo "FILE=arm64-images.txt" >> $GITHUB_OUTPUT
            ALIYUN_NAMESPACE=$NAMESPACE_ARM64
          else
            echo "FILE=amd64-images.txt" >> $GITHUB_OUTPUT
            ALIYUN_NAMESPACE=$NAMESPACE_AMD64
          fi

      - name: Sync Images
        run: |
          FILE=${{ steps.list.outputs.FILE }}

          echo "Using file: $FILE"

          while read -r IMAGE; do
            [ -z "$IMAGE" ] && continue

            IMAGE_NAME_TAG="${IMAGE##*/}"
            TARGET_IMAGE="$ALIYUN_REGISTRY/$ALIYUN_NAMESPACE/$IMAGE_NAME_TAG"

            echo "Syncing $IMAGE -> $TARGET_IMAGE"

            docker pull --platform linux/${{ github.event.inputs.arch }} $IMAGE

            docker tag $IMAGE $TARGET_IMAGE
            docker push $TARGET_IMAGE

          done < $FILE

      - name: Job Finished
        run: echo "All images synced successfully."